// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWrj2MJU6EBnHirtVBjmUkaFI9JyO5xE',
    appId: '1:713213142324:android:468646f9cbe9e7fa607161',
    messagingSenderId: '713213142324',
    projectId: 'robo-vpn',
    databaseURL: 'https://robo-vpn.firebaseio.com',
    storageBucket: 'robo-vpn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUfv0Y54nWYbj1SF6bOD5Rde9W-EA8pI',
    appId: '1:713213142324:ios:bf81fdb7243cd319607161',
    messagingSenderId: '713213142324',
    projectId: 'robo-vpn',
    databaseURL: 'https://robo-vpn.firebaseio.com',
    storageBucket: 'robo-vpn.appspot.com',
    androidClientId: '713213142324-lk4ck18rtb6g2gpemhopnhthp4sumc5a.apps.googleusercontent.com',
    iosClientId: '713213142324-gppa38grfq5p2e7egrgqes8jg9ogr2cp.apps.googleusercontent.com',
    iosBundleId: 'com.nerdvpn.vpn.app',
  );
}
