name: nerdvpn
description: Nerd VPN v6.0
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  country_codes: ^2.2.0
  country_icons: ^2.0.2
  dart_ping: ^8.0.1
  dio: ^5.0.2
  easy_localization: ^3.0.1
  extended_tabs: ^4.0.2
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.4
  flutter_html: ^3.0.0-alpha.6
  flutter_inapp_purchase:
    git:
      url: https://github.com/nizwar/flutter_inapp_purchase.git
  google_fonts: ^4.0.3
  google_mobile_ads: ^2.3.0
  in_app_update: ^4.0.1
  lottie: ^2.2.0
  ndialog: ^4.3.0
  openvpn_flutter: ^1.2.2 
  package_info_plus: ^3.0.3
  provider: ^6.0.5
  pull_to_refresh_flutter3: ^2.0.1
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/images/maps/"
    - "assets/icons/"
    - "assets/animations/"
    - "assets/languages/"
    - "assets/html/"
